name: general_consultation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  appinio_video_player: ^1.2.2
  audio_waveforms: ^1.0.4
  # audioplayers: ^5.2.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.1.0
  easy_refresh: ^3.3.3+1
  equatable: ^2.0.5
  # file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_blurhash: ^0.8.2
  flutter_html: 3.0.0-beta.2
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  # font_awesome_flutter: ^10.6.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.6.4
  google_maps_flutter: ^2.2.3
  image_picker: ^1.0.4
  # intl_phone_number_input: ^0.7.3+1
  json_annotation: ^4.8.1
  nb_utils: ^6.0.6
  path_provider: ^2.0.11
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.2.0
  retrofit: ^3.0.1+1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  voice_message_package: ^2.1.4
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  photo_view: ^0.14.0
  internet_connection_checker: ^1.0.0+1
  audioplayers: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^4.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    # - family: Cairo
    #   fonts:
    #       - asset: assets/fonts/Cairo-Black.ttf
    #         weight: 900
    #       - asset: assets/fonts/Cairo-ExtraBold.ttf
    #         weight: 800
    #       - asset: assets/fonts/Cairo-Bold.ttf
    #         weight: 700
    #       - asset: assets/fonts/Cairo-SemiBold.ttf
    #         weight: 600
    #       - asset: assets/fonts/Cairo-Medium.ttf
    #         weight: 500
    #       - asset: assets/fonts/Cairo-Regular.ttf
    #         weight: 400
    #       - asset: assets/fonts/Cairo-Light.ttf
    #         weight: 300
    #       - asset: assets/fonts/Cairo-ExtraLight.ttf
    #         weight: 200
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
